"""posts table

Revision ID: 19ad9a8405ca
Revises: c3a6e10beb9d
Create Date: 2020-04-15 18:31:40.157504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ad9a8405ca'
down_revision = 'c3a6e10beb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rights', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rights')
    # ### end Alembic commands ###
